apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="de">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Kubernetes Nginx Demo</title>
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          max-width: 800px;
          margin: 50px auto;
          padding: 20px;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
        }
        .container {
          background: rgba(255, 255, 255, 0.1);
          padding: 40px;
          border-radius: 10px;
          box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
        }
        h1 {
          margin-top: 0;
          font-size: 2.5em;
        }
        .info {
          background: rgba(255, 255, 255, 0.2);
          padding: 20px;
          border-radius: 5px;
          margin: 20px 0;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>🚀 Welcome to Kubernetes!</h1>
        <p>This page is running in a nginx Pod in a KIND Cluster.</p>
        
        <div class="info">
          <h2>📦 Deployment Info</h2>
          <ul>
            <li>Container: nginx</li>
            <li>Cluster: KIND (Kubernetes in Docker)</li>
            <li>HTML via ConfigMap bereitgestellt</li>
          </ul>
        </div>
        
        <p><strong>Status:</strong> ✓ Pod läuft erfolgreich!</p>
      </div>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    configMap:
      name: nginx-html
  dnsPolicy: ClusterFirst
  restartPolicy: Always